kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: slb-brownfield-users
  labels:
    kubernetes.io/metadata.name: slb-brownfield-users
  annotations:
    mcm.ibm.com/accountID: id-mycluster-account
    mcm.ibm.com/type: System
    openshift.io/description: ''
    openshift.io/display-name: ''
    openshift.io/requester: 'kube:admin'
    openshift.io/sa.scc.mcs: 's0:c26,c25'
    openshift.io/sa.scc.supplemental-groups: 246000/10000
    openshift.io/sa.scc.uid-range: 246000/10000
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2023-05-31T15:06:39Z'
      fieldsType: FieldsV1
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:finalizers': {}
      subresource: finalize
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
